name: Build Docker Image

on: 
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2.4.2
    
    - name: print msg
      run: echo "Starting to build Docker Image for webserver"
    
    - name: Docker Build
      run: docker build -t nginx_hello:0.1 .

    - name: print msg
      run: echo "Build completed"

    - name: run container
      run: docker run -d -p 80:80 nginx_hello:0.1

    - name: Let access it
      run: curl http://127.0.0.1
    
    - name: push Image to container registry
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.REGISTRY_ACCESS_TOKEN }}
        docker push singymingy86/nginx_hello:0.1