name: Build-Scan-Push

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
     
    - name: print msg
      run: echo "Building Container Image:"

    - name: Get TAG from short GIT SHA
      id: gtag
      run: |
        echo  "::set-output name=TAG::$(git rev-parse --short $GITHUB_SHA)"
    
    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
 
    - name: Docker Build & tag for push
      run: |
         docker build -t nginx_hello:${{ steps.gtag.outputs.TAG }} .
         docker tag nginx_hello:${{ steps.gtag.outputs.TAG }} singymingy86/nginx_hello:${{ steps.gtag.outputs.TAG }}
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: "nginx_hello:${{ steps.gtag.outputs.TAG }}"
          format: 'table'
          exit-code: '2'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
    
    - name: Push to Registry
      run: docker push singymingy86/nginx_hello:${{ steps.gtag.outputs.TAG }}
    - name: Print Hello
      run: echo Hello

    
